<?php         
$this->title = "My Users";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'users', 
        'action'=>'add'));?>">Add new user</a></p>
<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->users as $user) : ?>
<tr>
    <td><?php echo $this->escape($user->title);?></td>
    <td><?php echo $this->escape($user->artist);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'users', 
            'action'=>'edit', 'id'=>$user->id_user));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'users', 
            'action'=>'delete', 'id'=>$user->id_user));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>